services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    # ZITADEL_MASTERKEY: 'SAcD5TY0QPp89ip28bZPfEA5WDxqmobx' # run tr -dc A-Za-z0-9 </dev/urandom | head -c 32
    command: "start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey ${MASTERKEY} --tlsMode disabled"
    environment:
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: ${ADMIN_USERNAME}
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: ${ADMIN_PASSWORD}
      ZITADEL_EXTERNALSECURE: true

    depends_on:
      db:
        condition: "service_healthy"
    ports:
      - "8090:8080"
    volumes:
      - "./zitadel-config.yaml:/zitadel-config.yaml:ro"
      - "./zitadel-secrets.yaml:/zitadel-secrets.yaml:ro"
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro"
  db:
    restart: "always"
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGUSER: ${PG_USER}
      PGPASSWORD: ${PG_PASSWORD}
    networks:
      - "zitadel"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgresuser"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    volumes:
      - "data:/pgdb/pgdb-data:rw"

networks:
  zitadel:

volumes:
  data:
